version: "3"

services:
  build-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: build_app
    env_file:
      - .env
    volumes:
      - "./app:/app"
    ports:
      - "7000:7000"
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"